#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sizer.lib import list_size
import sys, os

if len(sys.argv) == 1:
    print(f"unit: MB")
    list_size(os.getcwd(), unit = "MB", rnd = 2)
    
if len(sys.argv) == 2:
    print(f"unit: MB")
    list_size(sys.argv[1])
    
if len(sys.argv) == 3:
    print(f"unit: {sys.argv[2]}")
    list_size(sys.argv[1], 
        unit = sys.argv[2])
        
if len(sys.argv) == 4:
    print(f"unit: {sys.argv[2]}")
    list_size(sys.argv[1], 
        unit = sys.argv[2],
        rnd = sys.argv[3])

