#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sizer.lib import list_size
import sys, os

if len(sys.argv) == 1:
    print(f"unit: MB")
    list_size(os.getcwd(), unit = "MB", rnd = 2, to_excel = True)
    
if len(sys.argv) == 2:  #sizel "path inside my pwd"
    print(f"unit: MB")
    list_size(sys.argv[1],
              to_excel = True)
    
if len(sys.argv) == 3:  #sizel "folder inside pwd"  "mb"
    print(f"unit: {sys.argv[2].upper()}")
    list_size(sys.argv[1], 
        unit = sys.argv[2].upper(), 
        to_excel = True)
        
if len(sys.argv) == 4: # sizel "folder" "mb" 3 
    print(f"unit: {sys.argv[2].upper()}")
    list_size(sys.argv[1], 
        unit = sys.argv[2].upper(),
        rnd = sys.argv[3],
        to_excel = True)

